apiVersion: v1
kind: Pod
metadata:
 name: sunilweb1
 labels:
apiVersion: v1
kind: Pod
metadata:
 name: sunilweb1
 labels:
  sunil: web1
 namespace: sunil
spec:
 containers:
 - name: sunilcon1
   image: sunilsoni187/sunilmltapp:v1
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: sunilsvc1
 namespace: sunil
spec:
 type: NodePort
 selector:
  label:
   sunil: web1
 ports:
 - name: sunilsvc1
   port: 9999
   protocol: TCP
   targetPort: 80
