apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashualpod
  name: ashualpod
  namespace: ashu  #  namespace name 
spec:
  containers:
  - image: alpine
    name: ashualpod
    command: ["/bin/sh","-c","ping fb.com"]  #  command is replacement of Entrypoint data from dockerfile
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
