apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashuenvpod
  name: ashuenvpod
  namespace: ashu
spec:
  containers:
  - image: dockerashu/ashuweb:june182020
    name: ashuenvpod
    ports:
    - containerPort: 80
    env:
    - name: page  #  name of variable from Docker image 
      value: web3    #  we are replacing from web1 to web3 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
