apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashuenvpod
  name: ashuenvpod
  namespace: ashu
spec:
  containers:
  - image: dockerashu/ashuweb:june182020
    name: ashuenvpod
    ports:
    - containerPort: 80
    env:
    - name: page  #  name of variable from Docker image 
      valueFrom:
       configMapKeyRef:
        name: ashucm1  #  name of configmap we created 
        key: x   #  key of configmap   
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
