apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podx
  name: podx
  namespace: ashu  #  change 1
spec:
  containers:
  - image: nginx
    name: podx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---   #  change  3 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashuss1
  name: ashuss1
  namespace: ashu  # chage 2
spec:
  ports:
  - name: 7789-80
    port: 7789
    protocol: TCP
    targetPort: 80
  selector:
   run: podx   #  change 4
  type: NodePort
status:
  loadBalancer: {}
