FROM   alpine
#   we are using this image as base image 
#  if this image will not be present in Docker engine it will pull automcatically
MAINTAINER   ashutoshh@linux.com ,  9509957594
#  in case of some help you can contact 
#CMD  ping  8.8.8.8
ENTRYPOINT  ping  8.8.8.8
#  this will be my default  parent process 
#  and we cant replace it as command line argument 

