apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupod2
  name: ashupod2
spec:
  nodeName: ip-172-31-71-55.ec2.internal    # hostname / IP  or  worker node and it will be scheduled over there
  containers:
  - image: nginx
    name: ashupod2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
