apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 namespace: test
 name: ciscorole

rules:
 - apiGroups: ["","extensions","apps"]
   resources: ["deployments","replicasets","pods"]
   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
