apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 namespace: test
 name: deploy-app-binding

subjects:
 - kind: User
   name: kubernetes-admin
   apiGroup: ""
roleRef:
 kind: Role
 name: ciscorole
 apiGroup: ""
